### ISSUE TITLE
Wrong language in BroadcastReceiver (local notification)

### ISSUE THREAD

**Issue by PepaZapletal** [akexorcist/Localization#102]
Hi, 

I have a problem with the correct language in the notification. 

I have English as the default language. Now I set a new language german in the app. In the app, it's working okay.

But when the scheduled notification arrived then it's in English (default language). 

Should I set something? How can I fix it? I'm using LocalizationApplication.

Thanks for help.

**Comment by akexorcist** [comment]
@PepaZapletal Because context in Broadcast Receiver isn't localized context. So please add this extension function in your project.
```kotlin
fun Context.toLocalizedContext(): Context = LocalizationUtility.applyLocalizationConfig(this)
```
Then convert it before using `getString(resId: String)`

```kotlin
class SimpleBroadcastReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        val localizedContext = context.toLocalizedContext()
        val content = localizedContext.getString(R.string.hello_world)
        // Do something
    }
}
```

**Comment by akexorcist** [comment]
Good news. 2.1.9 is live with the `Context.toLocalizedContext()` extension function.
