### ISSUE TITLE
Using with Fragment

### ISSUE THREAD

**Issue by gencaysahinn** [akexorcist/Localization#11]
Thank you for library. I have a problem. I'm trying to use with fragment. I implemented with OnLocaleChangedListener but i got an error like below.

 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

**Comment by akexorcist** [comment]
You don't have to use in fragment. Just implement it on activity then it will affects with fragment automatically.
