### ISSUE TITLE
Doesn't Work when Using with Activity of Nested Fragments

### ISSUE THREAD

**Issue by ghost** [akexorcist/Localization#12]
I have **'MainActivity'** which have **Fragment A** within it , and **Fragment A** have **Fragment B** within it .
like this: 
-MainActivity
--Fragment A (replaced in frame layout with ID: **R.id.frame1**)
--Fragment B (replaced within fragment A xml frame layout with iD: **R.id.frame2**)

Now When i change language from Fragment B , it gives exception  that **no view found with id R.id.frame1 in Fragment B** ?

How to fix this issue ?

**Comment by akexorcist** [comment]
I added nested fragment in the last commit. please check it out.
