### ISSUE TITLE
Change Language from Fragment

### ISSUE THREAD

**Issue by BluestarCo** [akexorcist/Localization#120]
Hi
how to call setLanguage function from fragment for change language?

i have FragmentStatePagerAdapter for intro pages and i need to change language from child fragments

thanks.

**Comment by kylevessPL** [comment]
Call getActivity().setLanguage(lang)

**Comment by akexorcist** [comment]
You can call
`(getActivity() as? LocalizationActivity)?.setLanguage(language)`
