### ISSUE TITLE
Library doesn't work in Google Play Internal Testing

### ISSUE THREAD

**Issue by passmanagerapp** [akexorcist/Localization#121]
I don't know what I do wrongly, but when I upload the .aab file to Google Play internal sharing, and after testing the app it doesn't work.

**Comment by akexorcist** [comment]
Hi @passmanagerapp, did you disable language splitting? (see [Language resources optimization in Android App Bundle](https://github.com/akexorcist/Localization#language-resources-optimization-in-android-app-bundle))
