### ISSUE TITLE
"nds" doesnt work on API Level 18+19

### ISSUE THREAD

**Issue by DaRolla** [akexorcist/Localization#13]
hi there,

thanks for this wonderful lib. 

Right now I just want to name an issue, which I was able to solve myself.

I am developing an German app, so our default language is German, the locale is DE, the folder is values-de.

I want to use a German dialect, and therefor I need your lib.

The problem is that I need a language identifier to be used.

I do NOT want to use English (EN) or French (FR) as the app may be translated into English or French in the future.

So I used "nds". Everything works fine except for API level 18 and 19.

So I switched back to Tai (TH).

The only price I pay is that any German which has its device set to Thai language gets our German dialect.

Cheers,
DaRolla

**Comment by akexorcist** [comment]
Is it possible that nds does not support for API 18 & 19? If correct, I have no idea to make your app to support for nds because my library is depending on android system language.
