### ISSUE TITLE
Selected language not working on switching activities with different orientations.

### ISSUE THREAD

**Issue by farooqkhan003** [akexorcist/Localization#14]
If we open new activity with different orientation and came back to the previous activity, it does not show the selected language.

**Comment by Faisal-Naseer** [comment]
did you find any solution, I am facing the same issue?

**Comment by vishwas89** [comment]
anybody found solution, I am also facing same issue

**Comment by Faisal-Naseer** [comment]
Yes i tried by re-attaching the base context. You can try in particular
activity

@Override
protected void attachBaseContext(Context newBase) {
    prefS = PreferenceManager.getDefaultSharedPreferences(newBase);
    editor = prefS.edit();
    mcaGlobal = (MyApp)newBase.getApplicationContext();
    if(prefS.getBoolean("LangSet",false)){
        if(!prefS.getString("Lang","").equals("")){
            mcaGlobal.setLang(prefS.getString("Lang",""));
        }
    }
    lang=mcaGlobal.getLang();
    super.attachBaseContext(mContextWrapper.wrap(newBase,lang));


}

**Comment by Faisal-Naseer** [comment]
public class mContextWrapper extends ContextWrapper {
    public mContextWrapper(Context base){
        super(base);
    }

    @SuppressWarnings("deprecation")
    public static ContextWrapper wrap(Context context, String language) {
        Configuration config = context.getResources().getConfiguration();
        Locale sysLocale = null;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            sysLocale = getSystemLocale(config);
        } else {
            sysLocale = getSystemLocaleLegacy(config);
        }
        if (!language.equals("") && !sysLocale.getLanguage().equals(language)) {
            Locale locale = new Locale(language);
            Locale.setDefault(locale);
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                setSystemLocale(config, locale);
            } else {
                setSystemLocaleLegacy(config, locale);
            }
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
                context = context.createConfigurationContext(config);
            } else {
                context.getResources().updateConfiguration(config,
context.getResources().getDisplayMetrics());
            }
        }
        return new mContextWrapper(context);
    }

    @SuppressWarnings("deprecation")
    public static Locale getSystemLocaleLegacy(Configuration config){
        return config.locale;
    }

    @TargetApi(Build.VERSION_CODES.N)
    public static Locale getSystemLocale(Configuration config){
        return config.getLocales().get(0);
    }

    @SuppressWarnings("deprecation")
    public static void setSystemLocaleLegacy(Configuration config,
Locale locale){
        config.locale = locale;
    }

    @TargetApi(Build.VERSION_CODES.N)
    public static void setSystemLocale(Configuration config, Locale locale){
        config.setLocale(locale);
    }
}

**Comment by vishwas89** [comment]
thanks for the reply 

Actually i have lot of fragments on Activity 1 and there is another Activity 2 which default orientation to landscape when i  return to Activity 1 (which is in PORTRAIT mode containing fragment) all the fragment language get change can you send the full code please  please help
