### ISSUE TITLE
Can't integrate with the Latest Version

### ISSUE THREAD

**Issue by moski** [akexorcist/Localization#18]
I keep getting the following error when trying to use the latest version

14:07:57.268 [INFO] [com.android.build.gradle.internal.ApplicationTaskManager] processing com/akexorcist/localizationactivity/BlankDummyActivity.class...
14:07:57.271 [ERROR] [org.gradle.api.Project] Dex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
    UNEXPECTED TOP-LEVEL EXCEPTION:

I currently have the following in my Grade file:

`compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }`

**Comment by akexorcist** [comment]
I fix it in 1.2.2, please check it.
