### ISSUE TITLE
Support for API 16

### ISSUE THREAD

**Issue by indy1515** [akexorcist/Localization#19]
Is it possible that this library can support API 16 (4.2.2) which is about 2.2%?

**Comment by akexorcist** [comment]
My library need recreate() method in activity class that include in api 17 or above.

**Comment by Kobzol** [comment]
Recreate was added in API 11 (https://developer.android.com/reference/android/app/Activity#recreate()), or is it some other method?

**Comment by alacoo** [comment]
Recreate was added in API 11 
and you can use context.getResources().updateConfiguration()
instants of context.createConfigurationContext() in api 16
