### ISSUE TITLE
Pull logic from LocalizationActivity...

### ISSUE THREAD

**Issue by consp1racy** [akexorcist/Localization#2]
...into LocalizationDelegate which will hold all the state. LocalizationActivity would then delegate all the work to this object.

See how AppCompatActivity and AppCompatDelegate works.

The goal is to be able to leverage this library while avoiding the use of AppCompatActivity or the appcompat-v7 dependency altogether.

**Comment by akexorcist** [comment]
@consp1racy  Thank you for your feedback. Latest version I just added LocalizationDelegate for alternative solution. (Thanks @AleksanderMielczarek for this pull request). But developer must be exclude AppCompat v7 dependency from this library in build.gradle to avoid it.
