### ISSUE TITLE
Failed to integrate latest version 

### ISSUE THREAD

**Issue by Akshata1812** [akexorcist/Localization#22]
My current compile version is 25 and build tool version is 25.0.2. while integrating latest library version(com.akexorcist:localizationactivity:1.2.2), I am getting below error. 

Error:Could not find com.android.support:appcompat-v7:26.1.0.
Required by:
    project :app
    project :app > com.android.support:design:25.3.1
    project :app > project :cropper

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

**Comment by akexorcist** [comment]
Just update to AndroidX in 1.2.3

**Note**: I've changed the dependency name from `com.akexorcist:localizationactivity` to `com.akexorcist.localization`. Please see more info the readme.
