### ISSUE TITLE
After switching the RTL language, the layout direction does not automatically update 

### ISSUE THREAD

**Issue by tcqq** [akexorcist/Localization#24]
The `en` language layout direction is from left to right, `ar` language is from right to left, when I switch from `en` to `ar`, the layout does not automatically change from left to right to right to left.

**Comment by tcqq** [comment]
#23 This issue is fixed.

**Comment by ijoshivaibhav** [comment]
> #23 This issue is fixed.

Hello,
I am still facing this issue in 1.2.2 version

**Comment by vuptt** [comment]
Hi team, 
I have the same issue in version 1.2.10
