### ISSUE TITLE
currency value multiplies by 100 times

### ISSUE THREAD

**Issue by fahmiyuseri** [akexorcist/Localization#26]
When I am changing the language from English to Cambodian Khmer language,the currency value increases by 100 times. When Send 1USD then showing 100USD in post method.
<img width="1084" alt="screen shot 2018-07-31 at 5 02 54 pm" src="https://user-images.githubusercontent.com/6570083/43449683-aa941486-94e3-11e8-892f-eaef509f3b0d.png">
![img_4254](https://user-images.githubusercontent.com/6570083/43449732-c4f48dec-94e3-11e8-8669-e22da31feee9.JPG)

**Comment by akexorcist** [comment]
That's look unrelated to the library... Please recheck your code to find out the problem
