### ISSUE TITLE
setDefaultLanguage does not work properly

### ISSUE THREAD

**Issue by shaniceweiwei** [akexorcist/Localization#28]
setDefaultLanguage added on top of super.onCreate() but it does not change to the language i wanted at first time launch of the app ( it is still english), until i kill it and relaunch it again.

**Comment by akexorcist** [comment]
Fixed in 1.2.3. 

**Note**: I've changed the dependency name from `com.akexorcist:localizationactivity` to `com.akexorcist.localization`. Please see more info the readme.
