### ISSUE TITLE
not working for android 6

### ISSUE THREAD

**Issue by YogeshTripathi5** [akexorcist/Localization#33]
library not working in marhsmallow devices....

**Comment by akexorcist** [comment]
Fixed in 1.2.3. 

**Note**: I've changed the dependency name from `com.akexorcist:localizationactivity` to `com.akexorcist.localization`. Please see more info the readme.

**Comment by MohamedT-Silverkey** [comment]
I have same issue and I use version 1.2.5

**Comment by akexorcist** [comment]
In 1.2.6, I tested in Android 6.0. If you still have some problem. Please tell me and provide some information about an issue.
