### ISSUE TITLE
App launch in Gujarati language instead of English in some devices(Moto G6,Mi A1).

### ISSUE THREAD

**Issue by dharmesh395** [akexorcist/Localization#34]
I have used three languages in my app and those are English, Hindi and Gujarati. In some devices(Moto G6 Android os 8.0 & Mi A1 os 9.0) app launched in Gujarati language instead of English. I want to launch app in English after installation. 

Current device language is English.
This function return Gujarati language.
getCurrentLanguage().getLanguage();

**Comment by Jaypatelbond** [comment]
@dharmesh395 
set the default language to english.
`setDefaultLanguage("en");`
