### ISSUE TITLE
Library Not Working Using Kotlin Programming Language

### ISSUE THREAD

**Issue by wikodhawi** [akexorcist/Localization#35]
I don't understand, I try  using Java and it worked well. But when I try using Kotlin nothing happened

` 

class MainActivity : LocalizationActivity() {

override fun onCreate(savedInstanceState: Bundle?) {

        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        lblTitleMain.setOnClickListener(View.OnClickListener {
            setLanguage("in")
        })
    }
}`
 

Am I do something wrong? I just want to change TextView when it clicked

**Comment by ipodib** [comment]
Observing the same issue.

**Comment by KhinThiriSoe** [comment]
it also happened to me

**Comment by SohailZahidGit** [comment]
If you are working with kotlin and dagger its giving this error ` could not find Fragment constructor`
