### ISSUE TITLE
Not working on Nougat OS

### ISSUE THREAD

**Issue by ghost** [akexorcist/Localization#37]
Hello,
i finded issue was not working on Nougat OS using version 1.2.2.
Please help me.

**Comment by iamkdblue** [comment]
@yovi-ep can add your code here?

**Comment by housesr** [comment]
@yovi-ep try downgrading appcompat to 1.0.2, it works for me. If you use com.google.android.material, don't forget to downgrade it as well since it has appcompat as a dependency.

**Comment by akexorcist** [comment]
Fixed in 1.2.3. 

**Note**: I've changed the dependency name from `com.akexorcist:localizationactivity` to `com.akexorcist.localization`. Please see more info the readme.
