### ISSUE TITLE
App language is not change when change device language

### ISSUE THREAD

**Issue by dharmesh395** [akexorcist/Localization#40]
I have used three languages in my app and those are French, Dutch and English. When I change language from app at that time it is working fine but when I change device language then app language is not change. For eg. If my device language is french then app should be in french.

**Comment by akexorcist** [comment]
This library work separately with system language. Actually, there is no reason to change the app language by system language changing. 

If you want to do like that your app must change the system language. But most of use case is about change the language without change system language.
