### ISSUE TITLE
layout direction not changes in Xiaomi phone

### ISSUE THREAD

**Issue by sgmm0hammad** [akexorcist/Localization#43]
Hello, thanks for your good library.
When I use a RTL language in "Xiaomi Redmi Note 4X" phone, it changes strings correctly, but layout direction not changed.

**Comment by shenawynkov** [comment]
try this  already answer issue #27 
 @Override
    public void setContentView(@LayoutRes int layoutResID) {
        super.setContentView(layoutResID);
        View v = findViewById(android.R.id.content);
        if(v!=null) {
            Locale locale = LanguageSetting.getLanguage(this);
            v.setLayoutDirection(TextUtils.getLayoutDirectionFromLocale(locale));
        }
    }

**Comment by sgmm0hammad** [comment]
> try this already answer issue #27
> @override
> public void setContentView(@LayoutRes int layoutResID) {
> super.setContentView(layoutResID);
> View v = findViewById(android.R.id.content);
> if(v!=null) {
> Locale locale = LanguageSetting.getLanguage(this);
> v.setLayoutDirection(TextUtils.getLayoutDirectionFromLocale(locale));
> }
> }

I changed the layoutDirection in my baseAcrivity programmatically, and fixed.
however very Thank you.
