### ISSUE TITLE
Slow activity transition

### ISSUE THREAD

**Issue by prathanbomb** [akexorcist/Localization#44]
Does anyone found the transition between activity is a bit slower after extend Activity by LocalizationActivity?

**Comment by pragadeeshNIS** [comment]
Yes it is slow.

**Comment by akexorcist** [comment]
@prathanbomb You mean the Activity class, not even FragmentActivity?

**Comment by akexorcist** [comment]
I am not sure does it related to DummyActivity or not. But I removed it in version 1.2.5. So it should not be slow anymore
