### ISSUE TITLE
App Bundle Issue

### ISSUE THREAD

**Issue by sunnykinger** [akexorcist/Localization#49]
In case if you are using app bundle to publish your application on Play Store, then locale change won't work for certain languages. App Bundle splits the resources for languages as well based on device requirements. I was facing this issue and later solved it by adding the following to app's build.gradle file.

`android {
    bundle {
        language {
            enableSplit = false
        }
    }
}`

Please mention this for people who are using your library so they do not face the problem.

Good work with the library.

**Comment by akexorcist** [comment]
Thank you for your concern. I've updated this issue in readme

Unfortunately, the library doesn't support for split language in App Bundle automatically. You've to use the Additional Languages API in Play Core library to download the language before.

For more information about Additional Language API  : https://android-developers.googleblog.com/2019/03/the-latest-android-app-bundle-updates.html

**Comment by sunnykinger** [comment]
> Thank you for your concern. I've updated this issue in readme
> 
> Unfortunately, the library doesn't support for split language in App Bundle automatically. You've to use the Additional Languages API in Play Core library to download the language before.
> 
> For more information about Additional Language API : https://android-developers.googleblog.com/2019/03/the-latest-android-app-bundle-updates.html

Yes with downloading additional languages from Play Core Library can also solve the problem. 
I don't see any mentions of split app bundle on Readme
