### ISSUE TITLE
Locale Code with Country

### ISSUE THREAD

**Issue by winseyli** [akexorcist/Localization#5]
Hi. Great library.

For locale code with country, I found that it is not success to change the language if the locale code is embedded with country. I tested by modifying your sample app.

...
} else if (id == R.id.btn_china) {
            setLanguage("zh_TW");
....

And then I rename the folder under res folder from "values-zh" to "values-zh-rTW"

Run the app. And the test result is the language wont change.

**Comment by winseyli** [comment]
Any update?

**Comment by akexorcist** [comment]
Not yet now. But thank you for this feedback because my solution in this library is only store language, locale code isn't include. 

I will fix this problem later.

**Comment by dtvc** [comment]
I'm having the same problem
