### ISSUE TITLE
Dark Mode Problem With MODE_NIGHT_FOLLOW_SYSTEM Selected

### ISSUE THREAD

**Issue by berkayturanci** [akexorcist/Localization#52]
There is an error on the library where if user want to use Dark Mode with flag MODE_NIGHT_FOLLOW_SYSTEM. 

MODE_NIGHT_NO, MODE_NIGHT_YES or MODE_NIGHT_AUTO_BATTERY works fine and only problem occurs due to the selection of MODE_NIGHT_FOLLOW_SYSTEM. 

Once system dark mode is changed, the application did not restarted with proper dark mode theme in MODE_NIGHT_FOLLOW_SYSTEM selected.

The problem caused due to the Application class method overriding. 

Causes Error:

```
    @Override
    protected void attachBaseContext(Context base) {
        deviceLanguage = Util.getDeviceLanguage();
        super.attachBaseContext(localizationDelegate.attachBaseContext(base));
    }
```

Not Causes Error, but Language changing doesn't work in this way:

```
    @Override
    protected void attachBaseContext(Context base) {
        localizationDelegate.setDefaultLanguage(base, MainApp.getDeviceLanguage());
        localizationDelegate.attachBaseContext(base);
        super.attachBaseContext(base);
    }
```

Version: 1.2.4

**Comment by akexorcist** [comment]
Fixed on 1.2.5. 

Thank you so much for your feedback.
