### ISSUE TITLE
Support Api version 15

### ISSUE THREAD

**Issue by Alireza-Farahani** [akexorcist/Localization#54]
First, thank you for your work. I tested this library and it works great. But the library minSdkVersion is set to 16. I am working on an application that has millions of user supporting minSdkVersion 15. I tried to override this in manifest but as I expected, I got runtime error in an emulator on Api version 15.

`NoSuchMethodError: android.content.res.Configuration.setLocale`

This happens in your [LocalizationContext](https://github.com/akexorcist/Android-Localization/blob/master/localization/src/main/java/com/akexorcist/localizationactivity/core/LocalizationContext.kt#L21) Class. `Configuration.setLocale()` is added in Api 17 and previously this had been done with `Configuration.locale = ...`. If this is the only reason to set minSdk to 17, could you consider supporting Api version 15?

Also a question, if setLocale is defined in Api 17, how your library supports Api 16?

**Comment by akexorcist** [comment]
You make me surprising about minSdkVersion in your project!!

So Here you go! version 1.2.5 with minSdkVersion 14
