### ISSUE TITLE
Need to update README after #66 fix

### ISSUE THREAD

**Issue by Cardistrynow** [akexorcist/Localization#67]
After #66 fix README needs to be updated, because today I spent a lot of time to find what am I doing wrong, I saw that in change log it is written that issue with default language is fixed, but I still had it
Only when I found commit I discovered where my mistake was))

Change:

`override fun attachBaseContext(newBase: Context) {`
`⠀⠀⠀super.attachBaseContext(localizationDelegate.attachBaseContext(newBase))`
`}`

To:

`override fun attachBaseContext(newBase: Context) {`
`⠀⠀⠀super.attachBaseContext(localizationDelegate.attachBaseContext(newBase))`
`⠀⠀⠀if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {`
`⠀⠀⠀⠀⠀⠀applyOverrideConfiguration(localizationDelegate.updateConfigurationLocale(newBase))`
`⠀⠀⠀⠀⠀⠀super.attachBaseContext(newBase)`
`⠀⠀⠀} else {`
`⠀⠀⠀⠀⠀⠀super.attachBaseContext(localizationDelegate.attachBaseContext(newBase))`
`⠀⠀⠀}`
`}`

**Comment by akexorcist** [comment]
Updated. Thank you for your notice.
