### ISSUE TITLE
Add support for changing language without activity recreate

### ISSUE THREAD

**Issue by Shahjahan786** [akexorcist/Localization#70]
Please add support for changing language without activity recreation.
like [ActivityRecreationHelper](https://github.com/franmontiel/LocaleChanger/blob/master/library/src/main/java/com/franmontiel/localechanger/utils/ActivityRecreationHelper.java)

**Comment by sgallego** [comment]
You can do this with an extension function:

```
fun LocalizationActivityDelegate.setLanguageWithoutNotification(context: Context, newLocale: Locale) {

    val oldLocale = LanguageSetting.getLanguageWithDefault(
            context,
            LanguageSetting.getDefaultLanguage(context)
    )
    if (!isCurrentLanguageSetting(newLocale, oldLocale)) {
        LanguageSetting.setLanguage(activity, newLocale)
        // Dont notifiy current activity notifyLanguageChanged()
    }

}

private fun isCurrentLanguageSetting(newLocale: Locale, currentLocale: Locale): Boolean {
    return newLocale.toString() == currentLocale.toString()
}
```

**Comment by Shahjahan786** [comment]
> You can do this with an extension function:
> 
> ```
> fun LocalizationActivityDelegate.setLanguageWithoutNotification(context: Context, newLocale: Locale) {
> 
>     val oldLocale = LanguageSetting.getLanguageWithDefault(
>             context,
>             LanguageSetting.getDefaultLanguage(context)
>     )
>     if (!isCurrentLanguageSetting(newLocale, oldLocale)) {
>         LanguageSetting.setLanguage(activity, newLocale)
>         // Dont notifiy current activity notifyLanguageChanged()
>     }
> 
> }
> 
> private fun isCurrentLanguageSetting(newLocale: Locale, currentLocale: Locale): Boolean {
>     return newLocale.toString() == currentLocale.toString()
> }
> ```

What if app source code is in Java?

**Comment by sgallego** [comment]
I think you have to create a new class that extends `LocalizationActivityDelegate`. 
Add `setLanguageWithoutNotification` in the new class and use your custom class instead `LocalizationActivityDelegate`.

**Comment by Shahjahan786** [comment]
> setLanguageWithoutNotification

Ok Got it, Thanks @sgallego
