### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by xz-dev** [akexorcist/Localization#72]
I use Application to setting my app as [README](https://github.com/akexorcist/Localization#new-123-or-higher) saying.
But when the System Theme has changed to dark/light theme, my app will not auto change theme.
If I do not set Application and just [use LocalizationApplication](https://github.com/akexorcist/Localization#old-122), my app won't go wrong.

**Comment by DanielNovak** [comment]
I can confirm I am seeing the same issue - changing to dark mode will relaunch the activities, but the dark mode is not enabled. Restarting the process will fix it. I had my own language switching code and it has the same issue as this library...

**Comment by DanielNovak** [comment]
I found the issue in your code: https://github.com/akexorcist/Localization/blob/ed371bed0847cb306a08d67ce186615f29a8802e/localization/src/main/java/com/akexorcist/localizationactivity/core/LocalizationContext.kt#L17
You can't create the Configuration instance this way. You need to use Configuration() and only set the Locale. **You only need to specify the values you would like to modify**. The javadoc explains is:

> 
> /**
>      * Return a new Context object for the current Context but whose resources
>      * are adjusted to match the given Configuration.  Each call to this method
>      * returns a new instance of a Context object; Context objects are not
>      * shared, however common state (ClassLoader, other Resources for the
>      * same configuration) may be so the Context itself can be fairly lightweight.
>      *
>      * @param overrideConfiguration A {@link Configuration} specifying what
>      * values to modify in the base Configuration of the original Context's
>      * resources.  If the base configuration changes (such as due to an
>      * orientation change), the resources of this context will also change except
>      * for those that have been explicitly overridden with a value here.
>      *
>      * @return A {@link Context} with the given configuration override.
>      */
>     public abstract Context createConfigurationContext(
>             @NonNull Configuration overrideConfiguration);
>

**Comment by akexorcist** [comment]
From @DanielNovak suggestion. https://github.com/akexorcist/Localization/commit/32095d834bb99f793902118ad88230ad870663ce and https://github.com/akexorcist/Localization/commit/3a35ade5ade2238fc0074b6ca0f43ec7c474b175 gonna be solve this problem

But I have to do the full testing before release this because there're a lot of changes from these code.

**Comment by juliocbcotta** [comment]
> From @DanielNovak suggestion. [32095d8](https://github.com/akexorcist/Localization/commit/32095d834bb99f793902118ad88230ad870663ce) and [3a35ade](https://github.com/akexorcist/Localization/commit/3a35ade5ade2238fc0074b6ca0f43ec7c474b175) gonna be solve this problem
> 
> But I have to do the full testing before release this because there're a lot of changes from these code.

Do you plan in releasing a new version soon ? Or at least an alpha or snapshot?

**Comment by akexorcist** [comment]
@BugsBunnyBR Yes, soon. 

But if you want to try the early release version. Try [JitPack](https://jitpack.io/)

```groovy
// build.gradle (project)
allprojects {
    repositories {
        /* ... */
	maven { url 'https://jitpack.io' }
    }
}

// build.gradle (app: module)
dependencies {
    /* ... */
    implementation 'com.github.akexorcist:Localization:develop-SNAPSHOT'
}
```

**Comment by akexorcist** [comment]
@xz-dev @DanielNovak @BugsBunnyBR Good news, 1.2.7 is rolling out
