### ISSUE TITLE
Not work when switching system dark theme using compose isSystemInDarkTheme().

### ISSUE THREAD

**Issue by ccmtmp** [akexorcist/Localization#75]
As title and I use below : 
- LocalizationActivity
- LocalizationApplication

Can change language, but cannot switch dark theme (compose's isSystemInDarkTheme()).

**Comment by akexorcist** [comment]
Fix in https://github.com/akexorcist/Localization/commit/32095d834bb99f793902118ad88230ad870663ce and https://github.com/akexorcist/Localization/commit/3a35ade5ade2238fc0074b6ca0f43ec7c474b175 

But I have to do the full testing before release this because there're a lot of changes from these code.

**Comment by cmcheungapp** [comment]
Great, thanks!

**Comment by akexorcist** [comment]
Duplicate of #72

**Comment by akexorcist** [comment]
@ccmtmp @cmcheungapp 1.2.7 is rolling out!
