### ISSUE TITLE
Language Change not working in release

### ISSUE THREAD

**Issue by Aniljangir** [akexorcist/Localization#80]
All things are working fine in development phase but when we upload app on playstore than language change is not working.

**Comment by akexorcist** [comment]
Do you published the app in `.aab`? Because Android App Bundles will split your language resource for each user.

You have to disable the language splitting in the `build.gradle` to support the in-app language changes

```
android {
    bundle {
        language {
            enableSplit = false
        }
    }
}
```

**Comment by bannarisoftwares** [comment]
Hello @akexorcist , can you please mention that should have **enableSplit = false** in .aab release mode. My works after this changes

**Comment by akexorcist** [comment]
@bannarisoftwares I mentioned about App Bundle in [Language resources optimization in Android App Bundle - Readme](https://github.com/akexorcist/Localization#language-resources-optimization-in-android-app-bundle).

Or you have any more suggestion?

**Comment by bannarisoftwares** [comment]
Hi @akexorcist , My bad, i. didn't check in the readme. It's fine

**Comment by akexorcist** [comment]
@bannarisoftwares No problem
