### ISSUE TITLE
After using version 1.2.6 application crashes for release version while opening. For debug it works fine.

### ISSUE THREAD

**Issue by sushantp777** [akexorcist/Localization#84]
java.lang.NoClassDefFoundError: Failed resolution of: LZM;
        at com.akexorcist.localizationactivity.core.LanguageSetting.setDefaultLanguage(Unknown Source:2)

I am using APK for generation and not the APP bundle.

**Comment by akexorcist** [comment]
Everything work fine after enabled `minifyEnabled` and `shrinkResources` as you mentioned in #85 to build the example project in this repository as release version.

Can you clean up the project and delete `build` directory then build the release version again?

**Comment by sushantp777** [comment]
No no. You got me wrong. The issue is happening because we have set `minifyEnabled` and `shrinkResources` as true. When they are set false then the issue does not happen.  

After installing it directly crashes and gives me the mentioned error.

Is this happening because I am using MultiDex in my application?

**Comment by akexorcist** [comment]
@sushantp777 I'm not sure but it can be because I didn't use it. Can you remove it then test it again?

Why MultiDex still in your app? Still support for API Level lower than 21?

**Comment by sushantp777** [comment]
Yes, still my app supports API level 18. I cannot remove those parameters because they are used for production purposes.

**Comment by akexorcist** [comment]
@sushantp777 As I tested on Galaxy Nexus - Android 4.3 (API Level 18) with minify and MultiDex (with over 64k methods) are enable in release APK build. Everything work fine.

Could you give me more information? e.g, device or your app.

Also try to add these rules to keep the classes from minify (`proguard-rules.pro`) and MultiDex (`multiDexKeepFile`)

```
-keep class com.akexorcist.localizationactivity.** { *; }
-dontwarn com.akexorcist.localizationactivity.**
```

**Comment by sushantp777** [comment]
By using `android.jetifier.blacklist` in gradle.properties, I was able to build and run successfully. Hence closing this issue.

**Comment by akexorcist** [comment]
Thank you for your information. Will add this in the readme.

**Comment by akexorcist** [comment]
@sushantp777 Do you have another library which using android support, not AndroidX?
