### ISSUE TITLE
Exclude a language change in notification channel (Feature Request)

### ISSUE THREAD

**Issue by ghost** [akexorcist/Localization#86]
**Summary :** Exclude a language change in notification channel

**Step to Reproduce :**
1. Set device language to English
2. Setup a notification channel with English name (Let's say that the channel name is `"News"`)
3. Add `setLanguage("th")` to an activity
4. Send a test notification to that channel
5. Go to device settings > notification > [App Name] 
6. You will see **News** and **เบ็ดเตล็ด**

**Expected Results :**
can configure to exclude a language change in device settings > notification channel

**Actual Results :**
**News** and **เบ็ดเตล็ด** are displayed in notification device settings. That looks inconsistent.

**Comment by akexorcist** [comment]
Roger that

**Comment by akexorcist** [comment]
@mongkonsrisin In this case, notification channel should not be localized string resource. Because it doesn't changed by device language changes. 

For better solution, using english-only for notification channel with `translatable="false"`. 

```
<string name="announcement_channel" translatable="false">Announcement</string>
```

**Comment by ghost** [comment]
Thank you.
