### ISSUE TITLE
Exclude androidx not working

### ISSUE THREAD

**Issue by Faisal-Naseer** [akexorcist/Localization#87]
I am trying to exclude androidx using
```
implementation 'com.akexorcist:localization:1.2.6'{
        exclude group: 'androidx.core', module: 'core'
    }
```
But its not working. 

Error:
**Could not find method com.akexorcist:localization:1.2.6() for arguments [build_50vj7u0d7uoiw7pr116q9wmz$_run_closure3$_closure11@5fc0acca] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.**

**Comment by akexorcist** [comment]
Add the bracket around `com.akexorcist:localization:1.2.6`

```groovy
implementation ('com.akexorcist:localization:1.2.6') {
    exclude group: 'androidx.core', module: 'core'
}
```

**Comment by akexorcist** [comment]
I close this issue because there's no response for a month. If you still have a problem, please feel free to re-open it.
