### ISSUE TITLE
ltr and rtl

### ISSUE THREAD

**Issue by MostafaAnter** [akexorcist/Localization#9]
in version 1.0.9 when change language to rtl language all activities swiped automatically but in recent releases versions until change language to rtl language all activity keep ltr design why last version dont swap all activity like version 1.0.9 , thanks in advanced

**Comment by alahammad** [comment]
use version 1.0.13, he has issue with  new version.

**Comment by a-najar** [comment]
@MostafaAnter am facing the same problem do u find any solution

**Comment by a-najar** [comment]
@akexorcist  please if you can help us in this

**Comment by MostafaAnter** [comment]
@geniusforapp yup of course use this version of lib 
`compile 'com.akexorcist:localizationactivity:1.0.9'`
