### ISSUE TITLE
com.akexorcist.localizationactivity.core.LocalizationActivityDelegate.setLanguage (LocalizationActivityDelegate.java)

### ISSUE THREAD

**Issue by hpng6** [akexorcist/Localization#91]
app crashing.

**Comment by akexorcist** [comment]
@hpng6 Please provide more information about crashing. e.g, error log, test device, app version and how to reproduce.

**Comment by hpng6** [comment]
> @hpng6 Please provide more information about crashing. e.g, error log, test device, app version and how to reproduce.

Fatal Exception: java.lang.IllegalArgumentException
Parameter specified as non-null is null: method kotlin.p.d.g.f, parameter newLanguage
com.akexorcist.localizationactivity.core.LocalizationActivityDelegate.setLanguage (LocalizationActivityDelegate.java)
com.myapplication.activity.MainActivity.yeschangelanguage (MainActivity.java:720)
com.myapplication.activity.MainActivity.access$600 (MainActivity.java:133)
com.myapplication.activity.MainActivity$17.onClick (MainActivity.java:691)
cn.pedant.SweetAlert.SweetAlertDialog.onClick (SweetAlertDialog.java:685)
android.view.View.performClick (View.java:5204)
android.view.View$PerformClick.run (View.java:21153)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5421)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

**Comment by akexorcist** [comment]
@hpng6 Could you show that code? From error message, did you passed `null` into `setLanguage(...)`?

**Comment by akexorcist** [comment]
I close this issue because there's no response for a while. Feel free to reopen it if you still have an issue about this.
